import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { TodosProvider } from '../src/contexts/TodoContext';

const inter = Inter({ subsets: ['latin'] });

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TodosProvider>{children}</TodosProvider>
      </body>
    </html>
  );
}
